# Generated by Django 2.1.4 on 2019-03-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_auto_20190316_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rec_app.Hostel'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name_hostel',
            field=models.CharField(max_length=100),
        ),
    ]
